language: node_js
node_js:
   - "6"
   - "7"
   - "8"

before_install:
   - npm i -g npm@5.7.1

after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
